export const IMAGES = {
  onboard1: require("./onboard1.png"),
  onboard2: require("./onboard2.png"),
  onboard3: require("./onboard3.png"),
  home: require("./home.png"),
  plans: require("./plans.png"),
  wallet: require("./wallet.png"),
  feed: require("./feed.png"),
  account: require("./account.png"),
  riseLogo: require("./rise-logo.png"),
  planIntro: require("./createPlanIntro.png"),
  riseLogo2: require("./logo2.png"),
  housing: require("./housing.png"),
  newBorn: require("./newBorn.jpg"),
  savings: require("./savings.jpg"),
  wealth: require("./wealth.jpg"),
  travel: require("./travel.jpg"),
  education: require("./education.jpg"),
  business: require("./business.jpg"),
  union: require("./union.jpg"),
  gift: require("./gift.jpg"),
};
