export const routes = Object.freeze({
  auth: "auth",
  onboarding: "onboarding",
  createAccount1: "Create Account 1",
  createAccount2: "Create Account 2",
  createAccountSuccess: "Create Account Success",
  signin: "Sign In",
  setPin: "Set Pin",
  setPinSuccess: "Set Pin Success",
  app: "App",
  home: "Home",
  plans: "Plans",
  wallet: "Wallet",
  feed: "Feed",
  account: "Account",
  app2: "App 2",
  createPlanIntro: "Create a plan",
  createPlanGoalName: "Goal name",
  createPlanTargetAmount: "Target Amount",
  createPlanTargetDate: "Target Date",
  review: "Review",
  createPlanSuccess: "Create Plan Success",
  planDetail: "Plan Detail",
  splash: "splash",
});
